// Generated by scripts/generate-capability-outcome-policy.mjs.
// Do not edit manually. capability-outcome-policy.yaml is the source.

export const POLICY_VERSION = "v1.0";
export const ALLOWED_EVIDENCE_CHECK_IDS = [
  "count_gt_zero",
  "dev_task_requirement_terminal",
  "dev_task_scope_terminal",
  "file_exists",
  "hash_matches",
  "journal_event_exists",
  "schema_valid"
];
export const ALLOWED_BUSINESS_FIELDS = [
  "blocked_reason",
  "current_node",
  "node_substate",
  "review_followup",
  "review_status",
  "status",
  "verification_result"
];
export const POLICIES = [
  {
    "policy_id": "reconcile.apply:reconcile_drift_repaired:subtask",
    "capability_id": "reconcile.apply",
    "outcome_type": "reconcile_drift_repaired",
    "subject_type": "subtask",
    "write_target": "dev_task",
    "state_effects": {
      "current_node": "set_from_input_optional",
      "status": "set_from_input_optional",
      "node_substate": "set_from_input_optional",
      "blocked_reason": "set_from_input_optional"
    },
    "evidence_required": {
      "mode": "all",
      "items": [
        {
          "kind": "A",
          "source": "event_journal",
          "check_id": "journal_event_exists"
        }
      ]
    },
    "must_ask_refs": [],
    "guards": [
      "no_self_referential_event",
      "no_unclosed_outcome_dependency"
    ]
  },
  {
    "policy_id": "reconcile.apply:reconcile_quick_archive:subtask",
    "capability_id": "reconcile.apply",
    "outcome_type": "reconcile_quick_archive",
    "subject_type": "subtask",
    "write_target": "dev_task",
    "state_effects": {
      "status": "set:done",
      "current_node": "set:archive",
      "node_substate": "set:archived",
      "review_status": "set:passed"
    },
    "evidence_required": {
      "mode": "all",
      "items": [
        {
          "kind": "C",
          "source": "reconcile_report",
          "check_id": "hash_matches"
        }
      ]
    },
    "must_ask_refs": [],
    "guards": [
      "no_self_referential_event"
    ]
  },
  {
    "policy_id": "archive.quick_review:review_passed:subtask",
    "capability_id": "archive.quick_review",
    "outcome_type": "review_passed",
    "subject_type": "subtask",
    "write_target": "dev_task",
    "state_effects": {
      "current_node": "set:review",
      "status": "set:reviewing",
      "node_substate": "set:reviewed",
      "review_status": "set:passed"
    },
    "evidence_required": {
      "mode": "all",
      "items": [
        {
          "kind": "C",
          "source": "file",
          "check_id": "file_exists"
        }
      ]
    },
    "must_ask_refs": [],
    "guards": [
      "no_self_referential_event"
    ]
  },
  {
    "policy_id": "archive.quick_archive:archived:subtask",
    "capability_id": "archive.quick_archive",
    "outcome_type": "archived",
    "subject_type": "subtask",
    "write_target": "dev_task",
    "state_effects": {
      "status": "set:done",
      "current_node": "set:archive",
      "node_substate": "set:archived",
      "review_status": "set:passed"
    },
    "evidence_required": {
      "mode": "all",
      "items": [
        {
          "kind": "C",
          "source": "file",
          "check_id": "file_exists"
        }
      ]
    },
    "must_ask_refs": [],
    "guards": [
      "no_self_referential_event"
    ]
  },
  {
    "policy_id": "requirement.cancel:cancelled:requirement",
    "capability_id": "requirement.cancel",
    "outcome_type": "cancelled",
    "subject_type": "requirement",
    "write_target": "requirement_md",
    "state_effects": {
      "status": "set:cancelled"
    },
    "evidence_required": {
      "mode": "all",
      "items": [
        {
          "kind": "A",
          "source": "file",
          "check_id": "file_exists"
        }
      ]
    },
    "must_ask_refs": [
      "must_ask_9"
    ],
    "guards": [
      "no_self_referential_event",
      "requirement_cancel_terminal_protection"
    ]
  },
  {
    "policy_id": "requirement.defer:deferred:requirement",
    "capability_id": "requirement.defer",
    "outcome_type": "deferred",
    "subject_type": "requirement",
    "write_target": "requirement_md",
    "state_effects": {
      "status": "set:deferred"
    },
    "evidence_required": {
      "mode": "all",
      "items": [
        {
          "kind": "A",
          "source": "file",
          "check_id": "file_exists"
        }
      ]
    },
    "must_ask_refs": [
      "must_ask_9"
    ],
    "guards": [
      "no_self_referential_event",
      "requirement_defer_terminal_protection"
    ]
  },
  {
    "policy_id": "subtask.cancel:cancelled:subtask",
    "capability_id": "subtask.cancel",
    "outcome_type": "cancelled",
    "subject_type": "subtask",
    "write_target": "dev_task",
    "state_effects": {
      "status": "set:cancelled"
    },
    "evidence_required": {
      "mode": "all",
      "items": [
        {
          "kind": "A",
          "source": "file",
          "check_id": "file_exists"
        }
      ]
    },
    "must_ask_refs": [
      "must_ask_9"
    ],
    "guards": [
      "no_self_referential_event",
      "subtask_cancel_terminal_protection"
    ]
  },
  {
    "policy_id": "requirement.finalize:delivered:requirement",
    "capability_id": "requirement.finalize",
    "outcome_type": "delivered",
    "subject_type": "requirement",
    "write_target": "requirement_md",
    "state_effects": {
      "status": "set:delivered"
    },
    "evidence_required": {
      "mode": "any",
      "items": [
        {
          "kind": "C",
          "source": "dev_task_scope",
          "check_id": "dev_task_scope_terminal"
        },
        {
          "kind": "C",
          "source": "dev_task_requirement",
          "check_id": "dev_task_requirement_terminal"
        }
      ]
    },
    "must_ask_refs": [],
    "guards": [
      "no_self_referential_event",
      "requirement_finalize_expected_hash",
      "requirement_not_cancelled_or_deferred"
    ]
  },
  {
    "policy_id": "requirement.promote:planning:requirement",
    "capability_id": "requirement.promote",
    "outcome_type": "planning",
    "subject_type": "requirement",
    "write_target": "requirement_md",
    "state_effects": {
      "status": "set:planning"
    },
    "evidence_required": {
      "mode": "all",
      "items": [
        {
          "kind": "A",
          "source": "requirement_md",
          "check_id": "hash_matches"
        }
      ]
    },
    "must_ask_refs": [],
    "guards": [
      "no_self_referential_event",
      "requirement_promote_forward_only"
    ]
  },
  {
    "policy_id": "requirement.promote:delivering:requirement",
    "capability_id": "requirement.promote",
    "outcome_type": "delivering",
    "subject_type": "requirement",
    "write_target": "requirement_md",
    "state_effects": {
      "status": "set:delivering"
    },
    "evidence_required": {
      "mode": "all",
      "items": [
        {
          "kind": "A",
          "source": "event_journal",
          "check_id": "journal_event_exists"
        }
      ]
    },
    "must_ask_refs": [],
    "guards": [
      "no_self_referential_event",
      "requirement_promote_delivering_forward_only"
    ]
  }
];

export function resolveCapabilityOutcomePolicy({ capabilityId, outcomeType, subjectType }) {
  return POLICIES.find((policy) =>
    policy.status !== "disabled" &&
    policy.capability_id === capabilityId &&
    policy.outcome_type === outcomeType &&
    policy.subject_type === subjectType
  ) ?? null;
}

export function validateCapabilityOutcomePolicyShape(document) {
  const issues = [];
  if (!document || typeof document !== "object" || Array.isArray(document)) {
    return { ok: false, issues: ["policy document must be an object"] };
  }
  if (document.version !== "v1.0") issues.push("version must be v1.0");
  if (!Array.isArray(document.policies)) {
    issues.push("policies must be an array");
    return { ok: false, issues };
  }
  const seen = new Set();
  const subjectTypes = new Set(["requirement","subtask","task"]);
  const writeTargets = new Set(["dev_task","requirement_md"]);
  const evidenceKinds = new Set(["A","B","C"]);
  const checkIds = new Set(["file_exists","schema_valid","count_gt_zero","hash_matches","journal_event_exists","dev_task_scope_terminal","dev_task_requirement_terminal"]);
  const stateFields = new Set(["status","current_node","node_substate","review_status","blocked_reason","verification_result","review_followup"]);
  for (const [index, policy] of document.policies.entries()) {
    const prefix = `policies[${index}]`;
    for (const key of ["policy_id", "capability_id", "outcome_type", "subject_type", "write_target", "state_effects", "evidence_required", "must_ask_refs"]) {
      if (policy?.[key] === undefined) issues.push(`${prefix}.${key} is required`);
    }
    if (!subjectTypes.has(policy?.subject_type)) issues.push(`${prefix}.subject_type unknown: ${policy?.subject_type}`);
    if (!writeTargets.has(policy?.write_target)) issues.push(`${prefix}.write_target unknown: ${policy?.write_target}`);
    const tuple = `${policy?.capability_id}:${policy?.outcome_type}:${policy?.subject_type}`;
    if (seen.has(tuple)) issues.push(`duplicate policy tuple: ${tuple}`);
    seen.add(tuple);
    for (const field of Object.keys(policy?.state_effects ?? {})) {
      if (!stateFields.has(field)) issues.push(`${prefix}.state_effects unknown field: ${field}`);
    }
    if (!["none", "all", "any"].includes(policy?.evidence_required?.mode)) issues.push(`${prefix}.evidence_required.mode unknown: ${policy?.evidence_required?.mode}`);
    for (const [evidenceIndex, item] of (policy?.evidence_required?.items ?? []).entries()) {
      if (!evidenceKinds.has(item.kind)) issues.push(`${prefix}.evidence_required.items[${evidenceIndex}] unknown kind: ${item.kind}`);
      if (!checkIds.has(item.check_id)) issues.push(`${prefix}.evidence_required.items[${evidenceIndex}] unknown check_id: ${item.check_id}`);
    }
    if (!Array.isArray(policy?.must_ask_refs)) issues.push(`${prefix}.must_ask_refs must be an array`);
  }
  return { ok: issues.length === 0, issues };
}
